name: alarm_plus
description: Cross-platform alarm plugin with reliability-first Android exact alarms and iOS notification-based best-effort alarms.
version: 0.1.3
homepage: https://github.com/pratikPSB/alarm_plus
repository: https://github.com/pratikPSB/alarm_plus
issue_tracker: https://github.com/pratikPSB/alarm_plus/issues

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:

  plugin:
    platforms:
      android:
        package: com.psb.alarm_plus
        pluginClass: AlarmPlusPlugin
      ios:
        pluginClass: AlarmPlusPlugin

topics:
  - alarm
  - fullscreen-alarm
  - alarm-events
  - notification

screenshots:
  - description: 'Example of alarm_plus'
    path: alarm_plus_demo.png
